### ISSUE TITLE
"Inappropriate value for attribute "subject_alternative_names": element 0:" Error

### ISSUE THREAD

**Issue by naomichi-y** [azavea/terraform-aws-acm-certificate#10]
After upgrading terraform to 0.12, I got following error.

```
Error: Incorrect attribute value type

  on .terraform/modules/acm_api/main.tf line 4, in resource "aws_acm_certificate" "default":
   4:   subject_alternative_names = ["${var.subject_alternative_names}"]

Inappropriate value for attribute "subject_alternative_names": element 0:
string required
```

This problem is considered to be due to a change in list.
https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables

**Comment by hectcastro** [comment]
Thanks, we will be looking to add Terraform 0.12 support soon.

**Comment by Nightbr** [comment]
For Terraform 0.12 directly use the variable and it works:

`subject_alternative_names = var.subject_alternative_names`
