### ISSUE TITLE
module "cert": count variables are only valid within resources

### ISSUE THREAD

**Issue by Xtigyro** [azavea/terraform-aws-acm-certificate#2]
I've tried to use the module but it appears it has a severe bug:
`module "cert": count variables are only valid within resources`

**Comment by hectcastro** [comment]
Hey @Xtigyro, can you provide an example of what you're doing to get this error message? Are you using `count` within the context of a `module` instantiation?

**Comment by Xtigyro** [comment]
I've tried to use it for multiple certs creation - which I think the module probably does not support.
```
resource "aws_route53_zone" "default" {
  count = "${length(var.domains)}"
  name  = "${element(var.domains, count.index)}"
}

module "cert" {
  source                    = "./mods/mod-aws-acm-certificates"

  count                     = "${length(var.domains)}"
  domain_name               = "${element(var.domains, count.index)}"
  subject_alternative_names = ["${lookup(var.domain_sub_resources, "${element(var.domains, count.index)}")}"]
  hosted_zone_id            = "${aws_route53_zone.default.zone_id}"
  validation_record_ttl     = "60"
}
```

**Comment by hectcastro** [comment]
Ah, I believe that this is a limitation of Terraform. `count` is not supported for modules. See https://github.com/hashicorp/terraform/issues/953.

**Comment by Xtigyro** [comment]
@hectcastro Yes, indeed - which is a pity. I'm working on code which should be able to do that - not sure whether we can use your code - so that a module can be created which will support multiple cert creation.

**Comment by hectcastro** [comment]
Thanks for giving it a try any way. Please let us know if you run into any other issues we can help with.
