### ISSUE TITLE
Add create_before_destroy lifecycle to aws_acm_certificate resource

### ISSUE THREAD

**Issue by rbreslow** [azavea/terraform-aws-acm-certificate#7]
We should look into adding a `create_before_destroy` [lifecycle customization](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations) to the [`aws_acm_certificate`](https://github.com/azavea/terraform-aws-acm-certificate/tree/develop/main.tf#L1) resource.

This would help in a situation where, for example, you have a certificate associated with an application load balancer. You can't destroy the `aws_acm_certificate` resource if it's in use, and there won't be a certificate available that you can associate with the ALB listener to replace it.

**Comment by hectcastro** [comment]
Resolved by https://github.com/azavea/terraform-aws-acm-certificate/pull/15.
